export const COMMENT_CREATE_REQUEST = "ITEM_CREATE_REQUEST";
export const COMMENT_CREATE_SUCCESS = "ITEM_CREATE_SUCCESS";
export const COMMENT_CREATE_FAIL = "ITEM_CREATE_FAIL";
export const COMMENT_LIST_SUCCESS = "ITEM_LIST_SUCCESS";
export const COMMENT_LIST_REQUEST = "ITEM_LIST_REQUEST";
export const COMMENT_LIST_FAIL = "ITEM_LIST_FAIL";
